// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRp96Cvif_INtP3rqlSrjYWjP4iVSmOGA',
    appId: '1:581376880340:web:59803c5368d481d3759541',
    messagingSenderId: '581376880340',
    projectId: 'dog-park-project',
    authDomain: 'dog-park-project.firebaseapp.com',
    storageBucket: 'dog-park-project.appspot.com',
    measurementId: 'G-Q11FR7R6XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfqIZ8eTaxa4qnZ-YsoNxblPU1175HKhw',
    appId: '1:581376880340:android:0c6024c7fc918bc7759541',
    messagingSenderId: '581376880340',
    projectId: 'dog-park-project',
    storageBucket: 'dog-park-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Cbsawzypid4QsOAZRR6xJ1icAsGR5zg',
    appId: '1:581376880340:ios:ccbfa88605ae4e36759541',
    messagingSenderId: '581376880340',
    projectId: 'dog-park-project',
    storageBucket: 'dog-park-project.appspot.com',
    iosClientId: '581376880340-e5oorpk8hkcindgph6irpuu66ti5j747.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogsPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Cbsawzypid4QsOAZRR6xJ1icAsGR5zg',
    appId: '1:581376880340:ios:ccbfa88605ae4e36759541',
    messagingSenderId: '581376880340',
    projectId: 'dog-park-project',
    storageBucket: 'dog-park-project.appspot.com',
    iosClientId: '581376880340-e5oorpk8hkcindgph6irpuu66ti5j747.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogsPark',
  );
}
